language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps

script:
  - make all
